const accountCategories = [
  { id: 'CARD', description: 'Cartão' },
  { id: 'MONE', description: 'Dinheiro' },
  { id: 'SAVI', description: 'Poupança' },
  { id: 'MEAL', description: 'Cartão Alimentação' },
  { id: 'INVE', description: 'Depósito a Prazo' },
];

const irsCategories = [
  {
    id: 'DG',
    name: 'Despesas Gerais',
    iva: false,
    percentage: '35',
    max: '250',
  },
  { id: 'SD', name: 'Saúde', iva: false, percentage: '15', max: '1000' },
  { id: 'ED', name: 'Educação', iva: false, percentage: '30', max: '800' },
  { id: 'HB', name: 'Habitação', iva: false, percentage: '15', max: '502' },
  { id: 'LR', name: 'Lares', iva: false, percentage: '25', max: '403,75' },
  {
    id: 'RP',
    name: 'Reparação de Automóveis',
    iva: true,
    percentage: '15',
    max: '',
  },
  {
    id: 'RM',
    name: 'Reparação de Motociclos',
    iva: true,
    percentage: '15',
    max: '',
  },
  {
    id: 'RA',
    name: 'Restauração e Alojamento',
    iva: true,
    percentage: '15',
    max: '',
  },
  { id: 'CB', name: 'Cabeleireiros', iva: true, percentage: '15', max: '' },
  {
    id: 'AV',
    name: 'Atividades Veterinárias',
    iva: true,
    percentage: '15',
    max: '',
  },
  {
    id: 'PM',
    name: 'Passes Mensais',
    iva: true,
    percentage: '100',
    max: '250',
  },
  { id: 'GN', name: 'Ginásios', iva: true, percentage: '15', max: '' },
];

const expenseCategories = [
  { id: 'SUPE', name: 'Supermercado', irsCategory: 'DG' },
  { id: 'REND', name: 'Renda', irsCategory: 'HB' },
  { id: 'CONT', name: 'Casa', irsCategory: 'DG' },
  { id: 'MODA', name: 'Moda', irsCategory: 'DG' },
  { id: 'COMB', name: 'Combustível', irsCategory: 'DG' },
  { id: 'REST', name: 'Restauração', irsCategory: 'RA' },
  { id: 'SAID', name: 'Saídas', irsCategory: 'DG' },
  { id: 'DECO', name: 'Decoração', irsCategory: 'DG' },
  { id: 'VIAG', name: 'Viagens', irsCategory: 'DG' },
  { id: 'TECN', name: 'Tecnologia', irsCategory: 'DG' },
  { id: 'PREN', name: 'Prendas', irsCategory: 'DG' },
  { id: 'HOSP', name: 'Hospital', irsCategory: 'SD' },
  { id: 'BELE', name: 'Beleza', irsCategory: 'DG' },
  { id: 'DENT', name: 'Dentista', irsCategory: 'SD' },
  { id: 'DEPI', name: 'Depilação', irsCategory: 'CB' },
  { id: 'CABE', name: 'Cabeleireiros', irsCategory: 'CB' },
  { id: 'FARM', name: 'Farmácia', irsCategory: 'SD' },
  { id: 'PASS', name: 'Passe', irsCategory: 'PM' },
  { id: 'ESTA', name: 'Estacionamento', irsCategory: 'DG' },
  { id: 'TRAN', name: 'Transporte', irsCategory: 'DG' },
  { id: 'EDUC', name: 'Educação', irsCategory: 'ED' },
  { id: 'AUTO', name: 'Automóvel', irsCategory: 'RP' },
  { id: 'OUTR', name: 'Outros', irsCategory: 'DG' },
];

export { accountCategories, irsCategories, expenseCategories };
